# Base configuration
# Specific experiments (e.g., resnet_ffpp.yaml) can override these defaults.

# -----------------------------------------------------------------------------------------------------
# General Settings
# -----------------------------------------------------------------------------------------------------
project_name: "deepfake-detection"
seed: 42

# -----------------------------------------------------------------------------------------------------
# Data Configuration (for DeepfakeDataModule)
# -----------------------------------------------------------------------------------------------------
data:
  # data_dir: null                # REQUIRED: Path to processed frames (e.g., /path/to/data_frames/ffpp)
  label_dirs:
    REAL: 0
    FAKE: 1
  load_sequences: false           # Default: false (loads single frames [C,H,W])
  sequence_length: 16             # Used if load_sequences: true (sequence length T)
  sampling_stride: 1              # Used if load_sequences: true (stride between frames in sequence)
  max_frames_per_video: null      # Optional: max frames per video (for SingleFrameDataset)
  max_videos_per_split: null      # Optional: max videos per split (for SequenceDataset)

  # DataLoader parameters
  batch_size: 32
  num_workers: 4

  # Parameters for building transforms
  transform:
    img_size: 224                         # Input image H, W
    norm_mean: [0.485, 0.456, 0.406]      # ImageNet mean
    norm_std: [0.229, 0.224, 0.225]       # ImageNet std
    train_augmentations: true             # Enable/disable data augmentation for training

# -----------------------------------------------------------------------------------------------------
# Model Configuration (for DeepfakeClassifier)
# -----------------------------------------------------------------------------------------------------
model:
  # model_name: null          # Options: "resnet18_single_frame", "xception3d"
  
  # Parameters for optimizer and scheduler
  optimizer_name: "adam"      # Options: "adam", "sgd"
  learning_rate: 0.0001
  use_scheduler: false

# -----------------------------------------------------------------------------------------------------
# Settings for the PyTorch Lightning Trainer
# -----------------------------------------------------------------------------------------------------
trainer:
  accelerator: "auto"        # 'cpu', 'gpu', 'tpu', 'mps', 'auto'
  devices: "auto"            # E.g.: 1 (for 1 GPU), [0,1] (for GPUs 0 and 1), "auto"
  precision: bf16-mixed      # '16-mixed', 'bf16-mixed' (default), '32', '64'
  deterministic: false       # Enable for maximum reproducibility
  # max_epochs: 20
  # callbacks: []          

# -----------------------------------------------------------------------------------------------------
# Logging Configuration (for the Trainer's logger)
# -----------------------------------------------------------------------------------------------------
# logger:
  #   type: "tensorboard"
  #   args:
  #     save_dir: "./outputs"

# -----------------------------------------------------------------------------------------------------
# Output Directory
# -----------------------------------------------------------------------------------------------------
# output_dir: "./outputs"
