# Experiment: ResNet18 on FaceForensics++ (FFPP)

# -----------------------------------------------------------------------------------------------------
# General Settings
# -----------------------------------------------------------------------------------------------------
project_name: "deepfake-detection"
seed: 42

# -----------------------------------------------------------------------------------------------------
# Data Configuration (for DeepfakeDataModule)
# -----------------------------------------------------------------------------------------------------
data:
  data_dir: data_frames/ffpp          
  label_dirs:
    REAL: 0
    FAKE: 1
  load_sequences: True           # Default: false (loads single frames [C,H,W])
  sequence_length: 16             # Used if load_sequences: true (sequence length T)
  sampling_stride: 1              # Used if load_sequences: true (stride between frames in sequence)
  max_frames_per_video: null      # Optional: max frames per video (for SingleFrameDataset)
  max_videos_per_split: null      # Optional: max videos per split (for SequenceDataset)

  # DataLoader parameters
  batch_size: 2
  num_workers: 4

  # Parameters for building transforms
  transform:
    img_size: 224
    norm_mean: [0.485, 0.456, 0.406]
    norm_std: [0.229, 0.224, 0.225]
    train_augmentations: true

# -----------------------------------------------------------------------------------------------------
# Model Configuration (for DeepfakeClassifier)
# -----------------------------------------------------------------------------------------------------
model:
  model_name: xception3d
  num_classes: 1
  
  model_params: {}

  # Parameters for criterion
  criterion_name: "bce_logit_loss"
  criterion_params: {}

  # Parameters for optimizer and scheduler
  optimizer_name: "sgd"
  optimizer_params:
    weight_decay: 0.01
    lr: 0.045
    momentum: 0.9

  # Parameters for learning rate scheduler
  use_scheduler: true
  scheduler_name: "step"
  scheduler_params:
    step_size: 2
    gamma: 0.94

  accuracy_task: "binary"
  accuracy_task_params: {}

# -----------------------------------------------------------------------------------------------------
# Settings for the PyTorch Lightning Trainer
# -----------------------------------------------------------------------------------------------------
trainer:
  accelerator: "auto"
  devices: 2
  precision: bf16-mixed
  deterministic: false
  max_epochs: 250
  callbacks:
    early_stopping:
      patience: 10

# -----------------------------------------------------------------------------------------------------
# Logging Configuration (for the Trainer's logger)
# -----------------------------------------------------------------------------------------------------
logger:
  type: "tensorboard"

# -----------------------------------------------------------------------------
# Settings for the execution
# -----------------------------------------------------------------------------

output_dir: "./outputs"
